version: "3.7"




services:
  mariadb:
    build: .
    ports:
      - "3306"
    container_name:
    depends_on:
      - 
    env_file:
      - 
    networks:
      - 
    volumes:
      -  db-data:/var/lib/mysql
    
  nginx:
    build: .
    ports:
      - "443"
    container_name:
    depends_on:
      - 
    env_file:
      - 
    networks:
      - 
    volumes:
      - wordpress-data:/var/www/html
    
  wordpress:
    build: .
    ports:
      - "9000"
    container_name:
    depends_on:
      - 
    env_file:
      - 
    networks:
      - 
    volumes:
      -  wordpress-data:/var/www/html


volumes:
  db-data:
    driver: bind
    driver_opts:
      path: data/mariadb
      
  wordpress-data:
    driver: bind
    driver_opts:
      path: data/wordpress

networks:
  # The presence of these objects is sufficient to define them
  inception:

    
  
