version: "3.7"

services:
  mariadb:
    build: requeriments/mariadb/
    ports:
      - "3306"
    container_name: mari
    env_file:
      - .env
    networks:
      - inception
    volumes:
      -  db-data:/var/lib/mysql
    
  nginx:
    build: requeriments/nginx/
    ports:
      - "443"
    container_name: ginx
    depends_on:
      - wordpress
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - wordpress-data:/var/www/html
    
  wordpress:
    build: requeriments/wordpress/
    ports:
      - "9000"
    container_name: wp
    depends_on:
      - mariadb
    env_file:
      - .env
    networks:
      - inception
    volumes:
      -  wordpress-data:/var/www/html


volumes:
  db-data:
    driver: local
    driver_opts:
      device: data/mariadb
      type: none
      o: bind
      
  wordpress-data:
    driver: local
    driver_opts:
      device: data/wordpress
      type: none
      o: bind

networks:
  # The presence of these objects is sufficient to define them
  inception:
    driver: bridge

    
  
