version: "3.7"

services:
  mariadb:
    build: requeriments/mariadb/
    restart: always
    ports:
      - "3306:3306"
    container_name: mariadb
    env_file:
      - .env
    networks:
      - inception
    volumes:
      -  db-data:/var/lib/mysql
    
  nginx:
    build: requeriments/nginx/
    restart: always
    ports:
      - "443:443"
    container_name: nginx
    depends_on:
      - wordpress
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - wordpress-data:/var/www/html
    
  wordpress:
    build: requeriments/wordpress/
    restart: always
    ports:
      - "9000:9000"
    container_name: wordpress
    depends_on:
      - mariadb
    env_file:
      - .env
    networks:
      - inception
    volumes:
      -  wordpress-data:/var/www/html


volumes:
  db-data:
    driver: local
    driver_opts:
      device: data/vol_mariadb
      type: none
      o: bind
      
  wordpress-data:
    driver: local
    driver_opts:
      device: data/vol_wordpress
      type: none
      o: bind

networks:
  inception:
    name: inception
    driver: bridge

    
  
